// <auto-generated />
namespace QuizApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class nam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nam));
        
        string IMigrationMetadata.Id
        {
            get { return "202007101237545_nam"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
